version: '3.8'

services:

  postgres:
    build: build-postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "qr"
      POSTGRES_USER: "qr"
      POSTGRES_PASSWORD: "password"
      TZ: "Europe/Berlin"

  influxdb:
    image: influxdb:1.8.2
    container_name: influxdb
    restart: always
    ports:
      - 8086:8086
    volumes:
      - ./influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=qr
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password
      - INFLUXDB_USER=influxdb
      - INFLUXDB_USER_PASSWORD=password
      - INFLUXDB_READ_USER=reader
      - INFLUXDB_READ_USER_PASSWORD=password
      - TZ=Europe/Berlin

  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=SONIA
      - TZ=Europe/Berlin
    depends_on:
      - influxdb

  grafana-image-renderer:
    image: grafana/grafana-image-renderer:2.0.0
    container_name: grafana-image-renderer
    ports:
      - "8081:8081"
    environment:
      - ENABLE_METRICS=true
